<?php

use \Drupal\Core\Form\FormStateInterface;

/**
 * @param $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 * @return string
 */
function hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.hello':
            return '<p>' . t('In case you need help for the Hello module') . '</p>';
    }
}

/**
 * Fonction cron
 */
function hello_cron()
{
    $purge_days_number = \Drupal::config('hello.settings')->get('purge_days_number');
    if ($purge_days_number != 0) {
        \Drupal::database()->delete('hello_user_statistics')
            ->condition('time', REQUEST_TIME - $purge_days_number * (24 * 3600), '<')
            ->execute();
    }

    \Drupal::messenger()->addMessage(t('Hello cron.'));
}

/**
 * @param \Drupal\user\UserInterface $account
 *
 * @throws Exception
 */
function hello_user_login(\Drupal\user\UserInterface $account)
{
    \Drupal::messenger()->addMessage(t('Bienvenue %name',
        ['%name'=>$account->getAccountName()]));

    $data = \Drupal::database()->insert('hello_user_statistics')
        ->fields([
            'uid'    => $account->id(),
            'action' => '1',
            'time'   => REQUEST_TIME,
        ])
        ->execute();
}

/**
 * @param \Drupal\Core\Session\AccountProxy $account
 *
 * @throws Exception
 */
function hello_user_logout(\Drupal\Core\Session\AccountProxy $account)
{
   $data = \Drupal::database()->insert('hello_user_statistics')
       ->fields([
           'uid'    => $account->id(),
           'action' => '0',
           'time'   => REQUEST_TIME,
       ])
       ->execute();
}

/**
 * @param \Drupal\user\UserInterface $user
 */
function hello_user_delete(\Drupal\user\UserInterface $user)
{
    \Drupal::database()->delete('hello_user_statistics')
        ->condition('uid', $user->id())
        ->execute();
}

function hello_theme($existing, $type, $theme, $path)
{
    return [
        'hello_user_connexion' => [
            'template'  => 'hello-user-connexion',
            'variables' => [
                'user'    => NULL,
                'count' => NULL
            ]
        ]
    ];
}

/**
 * @param array $form
 * @param FormStateInterface $form_state
 *
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function hello_form_user_admin_settings_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state)
{
    $roles = \Drupal::entityTypeManager()->getStorage('user_role')->loadMultiple();

    unset($roles['anonymous']);

    $options = [];
    foreach ($roles as $role) {
        $options[$role->id()] = $role->label();
    }

    $form['user_statistics'] = [
        '#type'    => 'details',
        '#title'   => t('Choose role to track'),
        '#open'    => TRUE,
        '#weight' => -1,
    ];

    $form['user_statistics']['options'] = [
        '#type'          => 'checkboxes',
        '#options'       => $options,
        '#default_value' => \Drupal::config('hello.settings')->get('user_statistics_roles')
    ];

    $form['#submit'][] = 'hello_user_admin_settings_form_submit';

}

/**
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function hello_user_admin_settings_form_submit(array &$form, \Drupal\Core\Form\FormStateInterface $form_state)
{
    $options = $form_state->getValue('options');
    \Drupal::configFactory()->getEditable('hello.settings')
        ->set('user_statistics_roles', $options)->save();
}
