<?php

/**
 * @param $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 * @return string
 */
function hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.hello':
            return '<p>' . t('In case you need help for the Hello module') . '</p>';
    }
}

/**
 * Fonction cron
 */
function hello_cron()
{
    $purge_days_number = \Drupal::config('hello.settings')->get('purge_days_number');
    if ($purge_days_number != 0) {
        \Drupal::database()->delete('hello_user_statistics')
            ->condition('time', REQUEST_TIME - $purge_days_number * (24 * 3600), '<')
            ->execute();
    }

    \Drupal::messenger()->addMessage(t('Hello cron.'));
}

/**
 * @param \Drupal\user\UserInterface $account
 *
 * @throws Exception
 */
function hello_user_login(\Drupal\user\UserInterface $account)
{
    \Drupal::messenger()->addMessage(t('Bienvenue %name',
        ['%name'=>$account->getAccountName()]));

    $data = \Drupal::database()->insert('hello_user_statistics')
        ->fields([
            'uid'    => $account->id(),
            'action' => '1',
            'time'   => REQUEST_TIME,
        ])
        ->execute();
}

/**
 * @param \Drupal\Core\Session\AccountProxy $account
 *
 * @throws Exception
 */
function hello_user_logout(\Drupal\Core\Session\AccountProxy $account)
{
   $data = \Drupal::database()->insert('hello_user_statistics')
       ->fields([
           'uid'    => $account->id(),
           'action' => '0',
           'time'   => REQUEST_TIME,
       ])
       ->execute();
}

/**
 * @param \Drupal\user\UserInterface $user
 */
function hello_user_delete(\Drupal\user\UserInterface $user)
{
    \Drupal::database()->delete('hello_user_statistics')
        ->condition('uid', $user->id())
        ->execute();
}

function hello_theme($existing, $type, $theme, $path)
{
    return [
        'hello_user_connexion' => [
            'template'  => 'hello-user-connexion',
            'variables' => [
                'user'    => NULL,
                'count' => NULL
            ]
        ]
    ];
}
